name: Data Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  run-scrapers:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BBC scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          set -e
          python Backend/Database/Mongo/bbc_scraper.py

      - name: Run CNN scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          set -e
          python Backend/Database/Mongo/cnn_scraper.py

      - name: Run Al-Jazeera scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          set -e
          python Backend/Database/Mongo/aljazeera_scraper.py

      - name: Run The Guardian scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          set -e
          python Backend/Database/Mongo/theguardian_scraper.py

      - name: Run Sky News scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          set -e
          python Backend/Database/Mongo/skynews_scraper.py