name: Data Automation
on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 30  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Original Scraper
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python Backend/Database/Mongo/web_scraper.py